### ISSUE TITLE
RuntimeErorr: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by jaeyoung0909** [Huffon/pytorch-transformer-kor-eng#1]
안녕하세요! 
저는 이 모델의 정확도를 높히기 위해 open subtitles 데이터(약 140만 pairs)를 추가로 사용해서 학습시키고 있습니다. 
그러던 중 이러한 에러가 발생했습니다.

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main(args)
  File "main.py", line 30, in main
    trainer.train()
  File "/home/moonde/Documents/pytorch-transformer-kor-eng/trainer.py", line 53, in train
    for batch in self.train_iter:
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/field.py", line 237, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/field.py", line 359, in numericalize
    var = torch.tensor(arr, dtype=self.dtype, device=device)
RuntimeError: CUDA error: device-side assert triggered

혹시 비슷한 에러를 겪으신 적 있으신가요?
학습 시작하자 마자 나는게 아니라 한 epoch 돌기 전 몇십개의 batch 를 돌고 나서 다음 에러가 발생합니다.

**Comment by jaeyoung0909** [comment]
해당 에러는 trainer.py 의 
output = self.model(source, target[:, :-1])[0] 
에서 비슷한 에러가 나서 이 부분을 try except 로 무시하고 진행했을 때 났었습니다. 
try except 문을 빼면 다음과 같은 에러가 납니다.
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main(args)
  File "main.py", line 30, in main
    trainer.train()
  File "/home/moonde/Documents/pytorch-transformer-kor-eng/trainer.py", line 53, in train
    for batch in self.train_iter:
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/field.py", line 237, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/moonde/anaconda3/lib/python3.7/site-packages/torchtext/data/field.py", line 359, in numericalize
    var = torch.tensor(arr, dtype=self.dtype, device=device)
RuntimeError: CUDA error: device-side assert triggered

**Comment by Huffon** [comment]
안녕하세요 ! 먼저 저는 해당 에러를 맞닥뜨린 적은 없습니다.

몇 번의 검색을 해보니 데이터셋 구축 시에 Label 값과 관련한 문제인 것 같습니다.
https://github.com/pytorch/pytorch/issues/1204 이슈 중,

> It seems not only -1 but also class labels larger than n_classes are not allowed as t >= 0 && t < n_classes.

댓글과 관련한 문제인 것 같습니다. pickle 빌드 시, 데이터셋에 대한 Vocab 설정이 torchtext에 의해 잘 되지 않은 것이 아닌가 생각됩니다. 훈련 이전에 `build_pickles.py`는 실행시키셨나요?

만약 그럼에도 잘 되지 않는다면 Vocab과 DataLoader를 따로 구축하신 후 피딩해주는 것이 해결책이 되지 않을까 싶습니다 !

**Comment by jaeyoung0909** [comment]
그런것 같습니다. 데이터셋을 유심히 보니 몇가지 이상한 pair 가 섞여있었습니다 ㅎㅎ
감사합니다!
