### ISSUE TITLE
Prediction error

### ISSUE THREAD

**Issue by ChangNamAn** [Huffon/pytorch-transformer-kor-eng#4]
Hi Huffon,

I got the error for prediction below.

Traceback (most recent call last):
  File "predict.py", line 70, in <module>
    predict(option)
  File "predict.py", line 49, in predict
    eos_idx = int(torch.where(target[0] == eos_idx)[0][0])
IndexError: index 0 is out of bounds for dimension 0 with size 0

How can I resolve this issue?
When I saw the modification in pull requests, Parvez2017 requested you to commit some changes and I have applied a few codes of his changes to predict.py but the translation of prediction returned  the pretty bad result.
Please help me out for this issue.

Thanks in advance.

**Comment by ChangNamAn** [comment]
Hi Huffon,

It's working well after training again.

$ python predict.py
kor> 내일 여자친구를 만나러 가요
eng> I will meet my girlfriend tomorrow

Thanks.
